import React, {useCallback, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Background, Controls, Handle, MiniMap, Position, ReactFlow, addEdge, useEdgesState, useNodesState, type NodeProps, type Connection, type Node} from '@xyflow/react';
import '@xyflow/react/dist/style.css'; import './style.css';

type Data = Record<string, any> & {label?:string; state?:string; error?:string; onChange?:(id:string, patch:Record<string,any>)=>void};
type WorkflowNode = Node<Data>;
const port = {width:9,height:9,background:'#69d2a5',border:'2px solid #10141b'};
function Card({id,data,type}: NodeProps<WorkflowNode> & {type:string}) { const [open,setOpen]=useState(false); const change=(patch:Record<string,any>)=>data.onChange?.(id,patch); const badge=data.state||'idle';
  return <div className={`card ${type} ${badge}`}><div className="node-head"><span>{data.label||type}</span><i className={badge}/></div>
  {type==='textInput' && <textarea value={data.text||''} onChange={e=>change({text:e.target.value})} placeholder="Static workflow input"/>}
  {type==='template' && <><textarea value={data.template||''} onChange={e=>change({template:e.target.value})} placeholder="Use {{variable}} names matching input handles"/><small>Inputs: {(String(data.template||'').match(/{{\s*([^}]+)\s*}}/g)||['{{text}}']).map((x:string)=>x.slice(2,-2).trim()).join(', ')}</small>{[...new Set((String(data.template||'').match(/{{\s*([^}]+)\s*}}/g)||['{{text}}']).map((x:string)=>x.slice(2,-2).trim()))].map((key:string,i)=><Handle key={key} type="target" position={Position.Left} id={key} style={{...port,top:`${35+i*16}%`}}/>)}</>}
  {type==='append' && <><input value={data.prefix||''} onChange={e=>change({prefix:e.target.value})} placeholder="Prefix"/><input value={data.suffix||''} onChange={e=>change({suffix:e.target.value})} placeholder="Suffix"/></>}
  {type==='transform' && <><select value={data.operation||'trim'} onChange={e=>change({operation:e.target.value})}>{['trim','prepend','append','replace','regex_replace','strip_fences','first_code_block','extract_json'].map(x=><option key={x}>{x}</option>)}</select>{['prepend','append','replace','regex_replace'].includes(data.operation) && <input value={data.value||data.find||''} onChange={e=>change(data.operation.includes('replace')?{find:e.target.value}:{value:e.target.value})} placeholder={data.operation.includes('replace')?'Find':'Text'}/>}</>}
  {type==='condition' && <><select value={data.condition||'contains'} onChange={e=>change({condition:e.target.value})}>{['contains','equals','starts_with','ends_with','regex'].map(x=><option key={x}>{x}</option>)}</select><input value={data.value||''} onChange={e=>change({value:e.target.value})} placeholder="Match value"/></>}
  {type==='llm' && <><input value={data.model||''} onChange={e=>change({model:e.target.value})} placeholder="Model ID"/><button className="section" onClick={()=>setOpen(!open)}>System Prompt {open?'⌄':'›'}</button>{open&&<textarea value={data.systemPrompt||''} onChange={e=>change({systemPrompt:e.target.value})} placeholder="Instructions for this model"/>}<details><summary>Sampling</summary><div className="numbers">{[['temperature',.7],['top_p',.95],['top_k',64],['min_p',0],['repetition_penalty',1.05],['presence_penalty',0],['max_tokens',4096]].map(([key,val])=><label key={key}>{key}<input type="number" value={data[key]??val} onChange={e=>change({[key]:Number(e.target.value)})}/></label>)}</div></details></>}
  {type==='output' && <div className="output">{data.result||'Final response appears here.'}</div>}{data.error&&<div className="error">{data.error}</div>}
  {type!=='textInput' && type!=='template' && <Handle type="target" position={Position.Left} id={type==='llm'?'prompt':'text'} style={port}/>} {type==='condition'?<><Handle type="source" position={Position.Right} id="true" style={{...port,top:'42%'}}/><Handle type="source" position={Position.Right} id="false" style={{...port,top:'72%'}}/></>:<Handle type="source" position={Position.Right} id="text" style={port}/>}</div> }
const types=['textInput','llm','template','append','transform','condition','output']; const nodeTypes=Object.fromEntries(types.map(type=>[type,(p:NodeProps<WorkflowNode>)=><Card {...p} type={type}/>])) as any;
const initialNodes:any[]=[{id:'input',type:'textInput',position:{x:50,y:220},data:{label:'TEXT INPUT',text:'Review this code for problems.'}},{id:'llm',type:'llm',position:{x:360,y:160},data:{label:'LLM TASK',model:'gemma-4-12b',systemPrompt:'You are a careful software reviewer.'}},{id:'out',type:'output',position:{x:700,y:220},data:{label:'OUTPUT'}}]; const initialEdges:any[]=[{id:'e1',source:'input',target:'llm',targetHandle:'prompt'},{id:'e2',source:'llm',target:'out'}];
function App(){const [nodes,setNodes,onNodesChange]=useNodesState(initialNodes);const [edges,setEdges,onEdgesChange]=useEdgesState(initialEdges);const [name,setName]=useState('Untitled workflow');const [notice,setNotice]=useState('Ready');const [saved,setSaved]=useState<number|null>(null);
 const update=useCallback((id:string,patch:Data)=>setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,...patch}}:n)),[setNodes]); const decorated=useMemo(()=>nodes.map(n=>({...n,data:{...n.data,onChange:update}})),[nodes,update]);
 const graph=()=>({version:1,nodes:nodes.map(({id,type,position,data})=>({id,type,position,data:Object.fromEntries(Object.entries(data).filter(([k])=>k!=='onChange'&&k!=='state'&&k!=='error'&&k!=='result'))})),edges});
 const add=(type:string)=>setNodes(ns=>[...ns,{id:`${type}-${Date.now()}`,type,position:{x:150+Math.random()*450,y:100+Math.random()*400},data:{label:type.replace(/([A-Z])/g,' $1').toUpperCase()}}]);
 const run=async()=>{setNotice('Running workflow…');setNodes(ns=>ns.map(n=>({...n,data:{...n.data,state:'waiting',error:''}})));try{const r=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({graph:graph()})});const body=await r.json();if(!r.ok)throw Error(body.detail);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,state:body.states[n.id]?.status||'idle',error:body.states[n.id]?.error,result:n.type==='output'?body.outputs[n.id]:undefined}})));setNotice('Workflow completed');}catch(e:any){setNotice(e.message);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,state:'error',error:e.message}})));}};
 const save=async()=>{const payload={name,description:'',graph:graph()};const r=await fetch(saved?`/api/workflows/${saved}`:'/api/workflows',{method:saved?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();setSaved(b.id);setNotice('Workflow saved');};
 const exportJson=()=>{const blob=new Blob([JSON.stringify({name,description:'',graph:graph()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${name}.json`;a.click();URL.revokeObjectURL(a.href)};
 const importJson=(file:File)=>{const reader=new FileReader();reader.onload=()=>{const x=JSON.parse(String(reader.result));setName(x.name||'Imported workflow');setNodes(x.graph.nodes);setEdges(x.graph.edges);setSaved(null);setNotice('Workflow imported')};reader.readAsText(file)};
 return <main><header><div className="brand">NODE<span>.AI</span></div><input className="title" value={name} onChange={e=>setName(e.target.value)}/><div className="actions"><button onClick={()=>setNodes([])}>New</button><label className="button">Import<input hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importJson(e.target.files[0])}/></label><button onClick={exportJson}>Export</button><button onClick={save}>Save</button><button className="run" onClick={run}>▶ Run</button></div></header><aside><b>ADD NODES</b>{types.map(x=><button key={x} onClick={()=>add(x)}>+ {x.replace(/([A-Z])/g,' $1')}</button>)}<p>Connect handles to pass text. Template target handles use the variable name.</p></aside><section><ReactFlow nodes={decorated} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={(c:Connection)=>setEdges(es=>addEdge(c,es))} fitView><Background gap={24}/><Controls/><MiniMap/></ReactFlow></section><footer><span className={notice.includes('completed')?'good':''}>{notice}</span><span>Sequential deterministic execution · LLM endpoint stays server-side</span></footer></main>}; createRoot(document.getElementById('root')!).render(<App/>);
